# Generated by Django 4.1.4 on 2022-12-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
