# Generated by Django 4.1.4 on 2022-12-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
