# Generated by Django 4.1.4 on 2022-12-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('B', 'B'), ('S', 'S'), ('G', 'G'), ('P', 'P')], default='B', max_length=1),
        ),
    ]
