# Generated by Django 4.1.4 on 2022-12-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('B', 'B'), ('S', 'S'), ('G', 'G'), ('P', 'P')], default=[0], max_length=1),
        ),
    ]
