# Generated by Django 4.1.4 on 2022-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_customer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
