# Generated by Django 4.1.4 on 2022-12-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('year_of_birth', models.PositiveSmallIntegerField()),
                ('year_of_death', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
