# Generated by Django 4.1.4 on 2022-12-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_painting_artist_id_alter_painting_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artist'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.owner'),
        ),
    ]
