# Generated by Django 4.1.4 on 2022-12-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_painting_artist_id_alter_painting_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiredpainting',
            name='return_to_owner',
        ),
        migrations.AddField(
            model_name='painting',
            name='mth_to_rtn',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='painting',
            name='rtn_to_owner',
            field=models.BooleanField(default=False),
        ),
    ]
