# Generated by Django 4.1.4 on 2022-12-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_hiredpainting_return_to_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='hired',
            field=models.BooleanField(default=False),
        ),
    ]
