# Generated by Django 4.1.4 on 2022-12-31 08:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_hiredpainting_appl_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='submit_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 8, 9, 37, 255820, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
