# Generated by Django 4.1.4 on 2022-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_painting_return_date_painting_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
