# Generated by Django 4.1.4 on 2022-12-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_painting_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
